version: 2
project_name: filebeat

builds:
  - id: filebeat
    binary: filebeat
    main: ./filebeat/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags="static_build"
    env:
      - CGO_ENABLED=0

archives:
- format: tar.gz
  id: tar
  name_template: "{{.ProjectName }}_{{.Version }}_{{.Os }}_{{.Arch }}"
- format: zip
  id: zip
  name_template: "{{.ProjectName }}_{{.Version }}_{{.Os }}_{{.Arch }}"
